# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: longhorn
#   namespace: argocd
# spec:
#   project: default

#   source:
#     repoURL: https://charts.longhorn.io
#     chart: longhorn
#     targetRevision: v1.10.1   # Helm chart version
#     helm:
#       skipHooks: true
#       values: |
#         preUpgradeChecker:
#           jobEnabled: false
#           upgradeVersionCheck: false
        
#         defaultSettings:
#           defaultReplicaCount: 2
#           defaultDataPath: /var/lib/longhorn
#           storageOverProvisioningPercentage: 200
#           storageMinimalAvailablePercentage: 10
#           upgradeChecker: false
        
#         persistence:
#           defaultClass: true
#           defaultFsType: ext4
#           defaultClassReplicaCount: 2

#         csi:
#           attacherReplicaCount: 1      # Default: 3
#           provisionerReplicaCount: 1   # Default: 3
#           resizerReplicaCount: 1       # Default: 3
#           snapshotterReplicaCount: 1   # Default: 3
        
#         service:
#           ui:
#             type: NodePort
#             nodePort: 30090
        
#         longhornManager:
#           resources:
#             limits:
#               cpu: 500m
#               memory: 512Mi
#             requests:
#               cpu: 100m
#               memory: 256Mi
        
#         longhornDriver:
#           resources:
#             limits:
#               cpu: 500m
#               memory: 512Mi
#             requests:
#               cpu: 100m
#               memory: 256Mi
        
#         longhornUI:
#           replicas: 1
#           resources:
#             limits:
#               cpu: 200m
#               memory: 256Mi
#             requests:
#               cpu: 50m
#               memory: 128Mi

#   destination:
#     server: https://kubernetes.default.svc
#     namespace: longhorn-system

#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
