indexer:
  persistence:
    storageClass: "longhorn"
    size: 5Gi
  
wazuh:
  manager:
    persistence:
      storageClass: "longhorn"
      size: 5Gi

dashboard:
  service:
    type: NodePort
    port: 443
    nodePort: 30443