apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wazuh

# Reference base
resources:
  - github.com/wazuh/wazuh-kubernetes?ref=v4.14.1

# Patches for local environment
patches:
- path: storage-class.yaml
- path: indexer-resources.yaml
- path: wazuh-resources.yaml