namespace: wazuh

resources:
  - $(wazuh_repo)/envs/local-env

patchesStrategicMerge:
  - indexer-resources-patch.yaml
  - manager-resources-patch.yaml
  - dashboard-resources-patch.yaml
  - dashboard-service-patch.yaml
  - storage-patch.yaml
  - agent-daemonset.yaml

secretGenerator:
  - name: indexer-certs
    files:
      - ../../wazuh/certs/indexer_cluster/admin-cert.pem
      - ../../wazuh/certs/indexer_cluster/admin-key.pem
      - ../../wazuh/certs/indexer_cluster/root-ca.pem
      - ../../wazuh/certs/indexer_cluster/node-cert.pem
      - ../../wazuh/certs/indexer_cluster/node-key.pem
      - ../../wazuh/certs/indexer_cluster/transport-ca.pem
      - ../../wazuh/certs/indexer_cluster/http-ca.pem
      - ../../wazuh/certs/indexer_cluster/snapshots-ca.pem
      - ../../wazuh/certs/indexer_cluster/stats-ca.pem
      - ../../wazuh/certs/indexer_cluster/stats-key.pem
      - ../../wazuh/certs/indexer_cluster/stats-cert.pem
      - ../../wazuh/certs/indexer_cluster/snapshots-key.pem
      - ../../wazuh/certs/indexer_cluster/snapshots-cert.pem
      - ../../wazuh/certs/indexer_cluster/http-key.pem
      - ../../wazuh/certs/indexer_cluster/transport-key.pem
      - ../../wazuh/certs/indexer_cluster/node-ca.pem
  - name: dashboard-certs
    files:
      - ../../wazuh/certs/dashboard_http/cert.pem
      - ../../wazuh/certs/dashboard_http/key.pem

# Common labels (optional)
commonLabels:
  environment: local
  managed-by: argocd

# Common annotations (optional)
commonAnnotations:
  deployed-by: argocd
