apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wazuh

patchesStrategicMerge:
  - indexer-resources-patch.yaml
  - manager-resources-patch.yaml
  - dashboard-resources-patch.yaml
  - dashboard-service-patch.yaml
  - storage-patch.yaml
  - agent-daemonset.yaml

# Common labels (optional)
commonLabels:
  environment: local
  managed-by: argocd

# Common annotations (optional)
commonAnnotations:
  deployed-by: argocd
